# Change these first
owner: JLeon03 # Your GitHub organization or username, where this repository lives
repo: Monitor2 # The name of this repository

sites:
  - name: Google
    url: https://www.google.com

  - name: GitHub
    url: https://github.com

  - name: OpenAI
    url: https://openai.com

  - name: Sitio de prueba (fallo)
    url: https://este-sitio-no-existe-123456.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Monitor2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor2
  introTitle: "**Sistema de Monitoreo de Disponibilidad**"
  introMessage: Página de monitoreo desarrollada con Upptime y GitHub Actions para verificar automáticamente la disponibilidad de diferentes servicios web.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
